**Create a NumPy array::**

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,])
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
print(np.__version__)
#version of numpy

1.23.5


In [6]:
arr = np.array(42)
print(arr)

42


In [7]:
#1-D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
#2-D Array
arr = np.array([[4,5],[8,9]])
print(arr)

[[4 5]
 [8 9]]


In [9]:
#3-D Array
arr = np.array([[4,5],[8,9],[4,6]])
print(arr)

[[4 5]
 [8 9]
 [4 6]]


In [10]:
#Check Number of Dimensions
a = np.array(50)
b = np.array([1, 2, 3, 4, 5,6])
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
#Dimensional Arrays
arr = np.array([1, 2, 3, 4], ndmin = 4)
print(arr)

[[[[1 2 3 4]]]]


In [12]:
#number of dimensions
print(arr.ndim)

4


In [13]:
#Access Array Elements
arr = np.array([8,9,10,11,12])
print(arr[0])

8


In [14]:
# third and fourth elements from the following array and add them
print(arr[2]+arr[3])

21


In [15]:
#Access 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr[1,1])

7


In [16]:
#Negative Indexing
print(arr[-1, -1])

10


In [17]:
#Access 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])

6


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [22]:
#Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [23]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


**Data Type of an Array**

In [24]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [25]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [26]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


NumPy Array Copy vs View

In [27]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [28]:
#Check if Array Owns its Data
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [29]:
#Shape of an Array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [30]:
#Reshape From 1-D to 2-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
#Convert the array into a 1D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [34]:
#NumPy Array Iterating
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [35]:
#Joining NumPy Arrays
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [36]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [37]:
#NumPy Sorting Arrays
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [38]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']
