In [ ]:
import torch
import numpy as np

In [ ]:
data=[[1,2],[3,4]]
x_data= torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [ ]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
x_zeros= torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]])

In [ ]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[0.1626, 0.6713],
        [0.9034, 0.6422]])

In [ ]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.4378, 0.0625, 0.6294],
        [0.9461, 0.1892, 0.0622]])

In [ ]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
rand_tensor.shape

torch.Size([2, 3])

In [ ]:
rand_tensor.dtype

torch.float32

In [ ]:
rand_tensor.device

device(type='cpu')

In [ ]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [ ]:
 rand_tensor

tensor([[0.3069, 0.0838, 0.5987],
        [0.1243, 0.5177, 0.3607]])

In [ ]:
rand_tensor[:,1]=1
rand_tensor

tensor([[0.3069, 1.0000, 0.5987],
        [0.1243, 1.0000, 0.3607]])

In [ ]:
rand_tensor[0]

tensor([0.3069, 1.0000, 0.5987])

In [ ]:
rand_tensor[:,0]

tensor([0.3069, 0.1243])

In [ ]:
rand_tensor[...,-1]

tensor([0.5987, 0.3607])

In [ ]:
rand_tensor.sum()

tensor(3.3906)

In [ ]:
rand_tensor.sum().item()

3.3906478881835938

In [ ]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.3069, 1.0000, 0.5987, 0.0000, 0.0000, 0.0000],
        [0.1243, 1.0000, 0.3607, 0.0000, 0.0000, 0.0000]])

In [ ]:
t2= torch.cat([rand_tensor, zeros_tensor],dim=0)
t2

tensor([[0.3069, 1.0000, 0.5987],
        [0.1243, 1.0000, 0.3607],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [ ]:
rand_tensor.mul(ones_tensor)

tensor([[0.3069, 1.0000, 0.5987],
        [0.1243, 1.0000, 0.3607]])

In [ ]:
rand_tensor.matmul(rand_tensor.T)

tensor([[1.4527, 1.2541],
        [1.2541, 1.1455]])

In [ ]:
rand_tensor.add_(5)

tensor([[5.3069, 6.0000, 5.5987],
        [5.1243, 6.0000, 5.3607]])

In [ ]:
n= np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [ ]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [ ]:
t.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [ ]:
x = torch.empty(1)
print(x)

tensor([-2.4644e+22])


In [ ]:
x.size()

torch.Size([1])

In [ ]:
x = torch.empty(2,3)
print(x)

tensor([[-2.0393e-16,  4.5073e-41, -2.4647e+22],
        [ 3.1494e-41,  4.4842e-44,  0.0000e+00]])


In [ ]:
torch.empty(2,2,3)

tensor([[[-2.0393e-16,  4.5073e-41, -2.0393e-16],
         [ 4.5073e-41,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 3.1494e-41,  7.7052e+31,  7.2148e+22]]])

In [ ]:
y=x.view(6)
y

tensor([-2.0393e-16,  4.5073e-41, -2.4647e+22,  3.1494e-41,  4.4842e-44,
         0.0000e+00])

In [ ]:
z=x.view(1,-1)
z

tensor([[-2.0393e-16,  4.5073e-41, -2.4647e+22,  3.1494e-41,  4.4842e-44,
          0.0000e+00]])

In [ ]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [ ]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [ ]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
a*b

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
a/b

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
a[1,1].item()

1.0

In [ ]:
torch.full((2,3),50)

tensor([[50, 50, 50],
        [50, 50, 50]])